export const SIGN_IN = 'SIGN_IN';
export const SIGN_OUT = 'SIGN_OUT';
export const CREATE_STREAM = 'CREATE_STREAM_SUCCESS';
export const FETCH_STREAMS = 'FETCH_STREAMS_SUCCESS';
export const FETCH_STREAM = 'FETCH_STREAM_SUCCESS';
export const DELETE_STREAM = 'DELETE_STREAM_SUCCESS';
export const EDIT_STREAM = 'EDIT_STREAM_SUCCESS';